config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  root to: 'pages#home'

  # USER LOGIN
  # Devise is a gem for user authentication
  devise_for :users

  # USER PROFILE
  # resource :profile is singular which mean each user
  # has only one profile each, has many will be profiles
  resources :users do
    resource :profile
  end

  # USER PROFILE USER TYPE
  resources :users do
    resource :user_type, except: :destroy
  end


  get 'about', to: 'pages#about'
  get 'clients', to: 'pages#clients'

  # CONTACTS
  resources :contacts, only: [:create]
  get 'contact-us', to: 'contacts#new', as: 'new_contact'

  get 'login', to: 'pages#login'
  get 'products', to: 'pages#products'
  get 'services', to: 'pages#services'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, 
                     styles: { medium: "300x300>", thumb: "100x100>" }, 
                     default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # EACH USER HAS ONE PROFILE AND USER TYPE
  has_one :profile 
  has_attached_file :avatar, default_url: "avatar.png"
  # If the user is destroyed then the userposts will be destroyed as well
  has_many :userposts, dependent: :destroy
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
end

app/models/userpost.rb
class Userpost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protected
    def after_sign_in_path_for(resource)
      if @user.profile.nil?
        request.env['omniauth.origin'] || stored_location_for(resource) || new_user_profile_path(user_id: current_user.id)
 

      end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET request to /contact-us
  # Show new contact form page
  def new
    @contact = Contact.new
  end

  # POST request /contacts
  def create
    # Instantiate new Contact Object
    @contact = Contact.new(contact_params)
    puts "asad"
    if @contact.save # Saves to database and returns true or false
      first_name = params[:contact][:first_name]
      last_name = params[:contact][:last_name]
      email = params[:contact][:email]
      company_name = params[:contact][:company_name]
      body  = params[:contact][:comments]
      ContactMailer.contact_email(first_name, last_name, email, company_name, body).deliver # Calls contact_email function from ContactMailer class
      flash[:success] = "Message sent."# Changable :success
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end

  private
    # Collects data from form
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :company_name, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end
  def about
  end
  def clients
  end
  def login
  end
  def products
  end
  def services
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # DEVISE ACTION USED TO LOCKDOWN PAGES
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    @profile = Profile.new    
  end

  def create
    # User who is currently logged in 
    # this comes from the url
    # PATH NEEDS THIS CODE id: params[:user_id]
    @user = User.find( params[:user_id] )
    # Create profile link to user
    @profile = @user.build_profile( profile_params )

    if @profile.save 
      flash[:success] = "Profile Updated"
      redirect_to user_path(id: params[:user_id] )
    else
      render action: :new
    end
  end

  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end

  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if  @profile.update_attributes( profile_params )
      flash[:success] = "Profile updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :edit
    end
  end

  private
  # WHITELISTING THE FORM SO HACKER CANT ADD FORM FIELD
  # USES FOR MASS ASSIGN
  def profile_params
    params.require(:profile).permit(:avatar, :first_name, :last_name, :job_title, :phone_number, :description) 
  end

  def only_current_user
    @user = User.find( params[:user_id] )
    redirect_to(root_path) unless @user == current_user
  end
end

app/controllers/userposts_controller.rb
class UserpostsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # DEVISE ACTION USED TO LOCKDOWN PAGES
  before_action :authenticate_user!

  def index

  end

  def show
    @user = User.find( params[:id] ) 
    @userposts = @user.userposts.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Evotech Software Solutions"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def navbar_color
    if user_signed_in?
      "navbar-inverse".html_safe
    else
      "navbar-default".html_safe
    end
  end
  
  def navbar_icon_link
    unless user_signed_in?
      "/".html_safe
    end
  end

  def cp(path)
    "current-nav" if current_page?(path)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userposts_helper.rb
module UserpostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/show.html.erb
<% provide(:title, "#{@user.profile.first_name} #{@user.profile.last_name}") %>
<div class="container">
  <div class="row">
    <div class="col-md-3 text-left">
      <h2><%= @user.profile.first_name %> <%= @user.profile.last_name %></h2>
      <%= @user.profile.job_title %></h3>
      <div class="profile-block profile-description">
        <h3>Description</h3>
        <%= @user.profile.description %>
      </div>
      <div class="profile-block profile-contact-info">
        <h3>Contact information</h3>
        <%= @user.profile.phone_number %><br>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<% provide(:title,"Contact Us") %>
<header id="contactUsHeader">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h1><strong>CONTACT US</strong></h1>
			</div>
			<div class="col-md-10 col-md-offset-1">
				<h2>We love to hear from the people who use our software</h2>
			</div>
		</div>
	</div>
</header>

<section id="contactUsForm">
	<div class="container">
		<div class="row">
			<div class="col-md-12 text-center contactUsGetInTouch">
				<h2>Get in touch with us</h2>
			</div>	
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<%= form_for @contact do |f| %>
					<div class="form-group">
						<%= f.label "All fields are required(*)" %>
					</div>
					<div class="form-group">
						<%= f.label :first_name %>
						<%= f.text_field :first_name , class: 'form-control formFields' %>
					</div>
					<div class="form-group">
						<%= f.label :last_name %>
						<%= f.text_field :last_name , class: 'form-control formFields' %>
					</div>
					<div class="form-group">
						<%= f.label :email %>
						<%= f.text_field :email, class: 'form-control formFields' %>
					</div>
					<div class="form-group">
						<%= f.label :company_name %>
						<%= f.text_field :company_name, class: 'form-control formFields' %>
					</div>
					<div class="form-group">
						<%= f.label :comments %>
						<%= f.text_area :comments, class: 'form-control formFields' %>
					</div>
					<%= f.submit 'Submit',class: 'btn btn-warning form-control formFields'%>
				<% end %> 
			</div>
		</div>
	</div>
</section>

<section id="contactUsContacts">
	<div class="container">
		<div class="titleContactUs">
			<div class="row">
				<div class="col-md-10 col-md-offset-1">
					<h2>Contacts</h2>
				</div>
			</div>
		</div>
		<div class="container mainContactUs">
			<div class="row">
				<div class="col-md-4 col-s-12">
					<div class="contactUsBox">
						<i class="fa fa-4x fa-map-pin sr-icons" aria-hidden="true"></i>
						<h2>Address</h2>	
						<br>
						<h5><strong>Main Office</strong></h5>
						<p class="text-muted">Evotech Software Solutions, Inc.<br>Cenel Place Bldg. 3rd Floor<br>239 Gen Luna Corner Burgos St.<br>Concepcion, Malabon City 1470<br>Philippines</p>
					
						<br>
						<h5><strong>Software House</strong></h5>
						<p class="text-muted">Evotech Software Solutions, Inc.<br>18-A1 Saint Jude. Herrera St<br>Ibaba, Malabon City 1470<br>Philippines</p>
					</div>
				</div>
				<div class="col-md-4 col-s-12">
					<div class="contactUsBox">
						<i class="fa fa-4x fa-phone sr-icons" aria-hidden="true"></i>
						<h3>Phone</h3>	
						<br>
						<h5><strong>Main Office</strong></h5>
						<p class="text-muted">+ 63 (02) 287-1111<br>+ 63 (02) 984-7320<br>+ 63 (02) 984-9620</p>
						<br>
						<h5><strong>Software House</strong></h5>
						<p class="text-muted">+ 63 (02) 521-5160<br>+ 63 (02) 387-6526</p>
					</div>
				</div>
				<div class="col-md-4 col-s-12">
					<div class="contactUsBox">
						<i class="fa fa-4x fa-at sr-icons" aria-hidden="true"></i>
						<h3>Email</h3>	
						<br>
						<h5><strong>General Inquiries</strong></h5>
						<p class="text-muted">solutions@evolvesoftware.com.ph</p>
						<br>
						<h5><strong>Employment</strong></h5>
						<p class="text-muted">hr@evolvesoftware.com.ph</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="contactUsHeader">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h2>Already a customer?<br>Contact our support service via Support Room</h2>
			</div>
			<div class="col-md-10 col-md-offset-1">
				<br>
				<p>If you already use our software and have a question, just go to your Support Room and ask away. We typically answer all request within 24 hours. We are available in the office Monday - Friday from 9 a.m. to 5 p.m.</p>
			</div>
		</div>
	</div>
</section>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
	<div class="form-group">
		<%= f.label :avatar %>
		<%= f.file_field :avatar, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :job_title %>
		<%= f.text_field :job_title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit "Update Profile", class: 'btn btn-success' %>
	</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center"> Edit Profile here </h1>
				<div class="well">
					<%=	render 'form' %>
				</div>
		</div>
	</div>
</div>

app/views/profiles/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="text-center"> Create Profile here </h1>
			<div class="well">
				<%=	render 'form' %>
			</div>
	</div>
</div>

app/views/userposts/_userpost.html.erb
<div class="row">
	<div class="col-md-12">
		<ul class="list-unstyled">
			<li>
				<div class="well well-sm row white-bg">
					<div class="col-sm-2 text-center userpost_avatar">
						<%= image_tag @user.profile.avatar.url %>
					</div>
					<div class="col-sm-10">
						<p><%= link_to userpost.user.profile.first_name + " " + userpost.user.profile.last_name,userpost.user %></p>
						<p><%= userpost.content %></p>
						<span class="timestamp">
							Posted <%= time_ago_in_words(userpost.created_at) %> ago.
						</span>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.profile.first_name} #{@user.profile.last_name}") %>
<div class="container" id="userProfile">
  <div class="row">
    <aside class="col-md-3 text-left">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
      <div class="user-info-container">
        <h1 class="user-info">
          <span class="user-fullname d-block"><%= @user.profile.first_name %> <%= @user.profile.last_name %></span>
          <span class="user-jobTitle d-block"><%= @user.profile.job_title %></span>
        </h1>
      </div>
      <!-- di pa tapos -->
      <div class="profile-block profile-description">
        <h3>Description</h3>
        <%= @user.profile.description %>
      </div>
      <div class="profile-block profile-contact-info">
        <h3>Contact information</h3>
        <%= @user.profile.phone_number %><br>
      </div>
    </aside>
    <div class="col-md-8">
      <div class="well well-lg row">
        <% if @user.userposts.any? %>
          <h3>Feed (<%= @user.userposts.count %>)</h3>
          <%= render @userposts %>
          <%= will_paginate @userposts %>
        <% end %>
      </div>
    </div>
  </div>
</div>