config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  root to: 'pages#home'

  # USER LOGIN
  # Devise is a gem for user authentication
  devise_for :users

  # USER PROFILE
  # resource :profile is singular which mean each user
  # has only one profile each, has many will be profiles
  resources :users do
    resource :profile
  end

  # USER PROFILE USER TYPE
  resources :users do
    resource :user_type, except: :destroy
  end


  get 'about', to: 'pages#about'
  get 'clients', to: 'pages#clients'

  # CONTACTS
  resources :contacts, only: [:create]
  get 'contact-us', to: 'contacts#new', as: 'new_contact'

  get 'login', to: 'pages#login'
  get 'products', to: 'pages#products'
  get 'services', to: 'pages#services'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, 
                     styles: { medium: "300x300>", thumb: "100x100>" }, 
                     default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # EACH USER HAS ONE PROFILE AND USER TYPE
  has_one :profile 
  has_attached_file :avatar, default_url: "avatar.png"
  # If the user is destroyed then the userposts will be destroyed as well
  has_many :userposts, dependent: :destroy
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
end

app/models/userpost.rb
class Userpost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET request to /contact-us
  # Show new contact form page
  def new
    @contact = Contact.new
  end

  # POST request /contacts
  def create
    # Instantiate new Contact Object
    @contact = Contact.new(contact_params)
    puts "asad"
    if @contact.save # Saves to database and returns true or false
      first_name = params[:contact][:first_name]
      last_name = params[:contact][:last_name]
      email = params[:contact][:email]
      company_name = params[:contact][:company_name]
      body  = params[:contact][:comments]
      ContactMailer.contact_email(first_name, last_name, email, company_name, body).deliver # Calls contact_email function from ContactMailer class
      flash[:success] = "Message sent."# Changable :success
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end

  private
    # Collects data from form
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :company_name, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end
  def about
  end
  def clients
  end
  def login
  end
  def products
  end
  def services
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # DEVISE ACTION USED TO LOCKDOWN PAGES
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    @profile = Profile.new    
  end

  def create
    # User who is currently logged in 
    # this comes from the url
    # PATH NEEDS THIS CODE id: params[:user_id]
    @user = User.find( params[:user_id] )
    # Create profile link to user
    @profile = @user.build_profile( profile_params )

    if @profile.save 
      flash[:success] = "Profile Updated"
      redirect_to user_path(id: params[:user_id] )
    else
      render action: :new
    end
  end

  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end

  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if  @profile.update_attributes( profile_params )
      flash[:success] = "Profile updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :edit
    end
  end

  private
  # WHITELISTING THE FORM SO HACKER CANT ADD FORM FIELD
  # USES FOR MASS ASSIGN
  def profile_params
    params.require(:profile).permit(:avatar, :first_name, :last_name, :job_title, :phone_number, :description) 
  end

  def only_current_user
    @user = User.find( params[:user_id] )
    redirect_to(root_path) unless @user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # DEVISE ACTION USED TO LOCKDOWN PAGES
  before_action :authenticate_user!

  def index

  end

  def show
    @user = User.find( params[:id] ) 
    @userposts = @user.userposts.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Evotech Software Solutions"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def navbar_color
    if user_signed_in?
      "navbar-inverse".html_safe
    else
      "navbar-default".html_safe
    end
  end
  
  def navbar_icon_link
    unless user_signed_in?
      "/".html_safe
    end
  end

  def cp(path)
    "current-nav" if current_page?(path)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userposts_helper.rb
module UserpostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer id="homeFooter">
  <div class="container">
    <div class="row">
      <div class="col-md-4"> 
	      <span class="copyright">© Evotech Software Solutions, Inc. 2017</span>
      </div>
      <div class="col-md-4"> 
	<ul class="list-inline circle-buttons">
	  <li class="list-inline-item">
	    <a class="first-circle-button" href="#">
		    <i class="fa fa-twitter"></i>
	    </a>
	  </li>
	  <li class="list-inline-item">
	    <a href="#">
		    <i class="fa fa-facebook"></i>
	    </a>
	  </li>
	  <li class="list-inline-item">
	    <a href="#">
		    <i class="fa fa-linkedin"></i>
	    </a>
	  </li>
	</ul>
      </div>
      <div class="col-md-4"> 
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'shared/navigation' %>
    <!-- START OF ALERT MSG ################################################ -->
    <div class="container" style="position: absolute; padding:0; width:100%;">
      <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type} text-center" %>
      <% end %>
    </div>
    <!-- END OF ALERT MSG ################################################## -->
    <%= yield %>
    <% if !user_signed_in? %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title,"About") %>
ABOUT PAGE

app/views/pages/clients.html.erb
<% provide(:title,"Clients") %>

app/views/pages/home.html.erb
<header id="homeHeader">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h1><strong>WELCOME TO EVOTECH</strong></h1>
			</div>
			<div class="col-md-10 col-md-offset-1">
				<h2>Benefit from our experience</h2>
			</div>
		</div>
	</div>
</header>

<section id="homeAbout">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h2>We completely believe that the client's need is paramount</h2>
				<hr>
				<br>
			</div>
			<div class="col-md-8 col-md-offset-2">
				<p>We offer more than just features, but a way to achieve your goals, and the best means to help you achieve your goal is to find out as much as we can about your company and its needs, so we can come up with the best solution for you.</p>
				<br>
				<p>Let us work together and belong to the growing cluster of companies achieving their goal through technological advancement.</p>
				<br>
				<p><strong>Be part and benefit from our experience.</strong></p>
			</div>
		</div>
	</div>
</section>

<section id="homeApproaches">
	<div class="container titleApproaches">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h2>Our main approaches</h2>
				<hr>
				<br>
			</div>
		</div>
	</div>
	<div class="container mainApproaches">
		<div class="row">
			<div class="col-md-4 col-s-12">
				<div class="approachesBox">
					<i class="fa fa-5x fa-bullseye sr-icons" aria-hidden="true"></i>
				  <h3>Focus</h3>	
					<p class="text-muted">The very secret of success. We use technical approach to indentify problem areas and integrate analysis into functional business solutions and a technology to match them</p>
				</div>
			</div>
			<div class="col-md-4 col-s-12">
				<div class="approachesBox">
					<i class="fa fa-5x fa-arrows sr-icons" aria-hidden="true"></i>
				  <h3>Custom Development</h3>	
					<p class="text-muted">A Technology that meets your very needs. A standard to be set at ppar with your very own process</p>
				</div>
			</div>
			<div class="col-md-4 col-s-12">
				<div class="approachesBox">
					<i class="fa fa-5x fa-gears sr-icons" aria-hidden="true"></i>
				  <h3>Modular structure</h3>	
					<p class="text-muted">Pay only for the services that you need</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="homeTechPartners">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h2>We completely believe that the client's need is paramount</h1>
				<br>
			</div>
			<div class="col-md-4">
			</div>
		</div>
	</div>
</section>

app/views/pages/products.html.erb
<% provide(:title,"Products") %>

app/views/pages/services.html.erb
<% provide(:title,"Services") %>

app/views/shared/_navigation.html.erb
<nav class="navbar <%= navbar_color %> navbar-static-top navbar-fixed-top" id="mainNav" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
	<%= link_to navbar_icon_link , class: "navbar-brand" do %>
	  <!-- <i class="fa fa-group"></i> -->
	<% end %>
    </div>

    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
	<% if !user_signed_in? %> <!-- IF USER IS SIGNED IN -->
	  <li><%= link_to "ABOUT", about_path , class: cp(about_path) %></li>
	  <li><%= link_to "SERVICES", services_path, class: cp(services_path) %></li>
	  <li><%= link_to "PRODUCTS", products_path, class: cp(products_path) %></li>
	  <li><%= link_to "CLIENTS", clients_path, class: cp(clients_path) %></li>
	  <li><%= link_to "CONTACT US", new_contact_path, class: cp(new_contact_path) %></li>
	  <li><%= link_to "LOGIN", new_user_session_path, class: cp(new_user_session_path) %></li>
	<% else %>
	    <% if user_signed_in? %>
	      <% unless current_user.profile.nil? %>
		
	  <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		  <%= image_tag current_user.profile.avatar.url , class: 'navbar-avatar' %>
		</a>
	      <% end %>
	    <% end %>

	    <ul class="dropdown-menu">
	      <li><%= link_to "View Profile", user_path(id: current_user.id) %></li>
	      <li><%= link_to "Edit Profile", edit_user_profile_path(user_id: current_user.id) %></li>
	      <li><a href="#">Settings</a></li>
	      <li role="separator" class="divider"></li>
	      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	    </ul>
	  </li>
	<% end %><!-- END OF IF USER IS SIGNED IN -->
      </ul>
    </div>
  </div>
</nav>